### PR TITLE
Resolves issue #72

### LINKED ISSUE #72: Invalid TTL and name when record name is numeric
In [RFC1035](https://tools.ietf.org/html/rfc1035) the structure of an entry is defined as:

> ```
>     <domain-name><rr> [<comment>]
>     <blank><rr> [<comment>]
> ```
> If an entry for an RR begins with a blank, then the RR is assumed to be owned by the last stated owner.  If an RR entry begins with a < domain-name >, then the owner name is reset.
> 
> ```
> <rr> contents take one of the following forms:
>     [<TTL>] [<class>] <type> <RDATA>
>     [<class>] [<TTL>] <type> <RDATA>
> ```
> The RR begins with optional TTL and class fields, followed by a type and RDATA field appropriate to the type and class.  Class and type use the standard mnemonics, TTL is a decimal integer.  Omitted class and TTL values are default to the last explicitly stated values.

But when we pass an entry like `123 A 1.2.3.4` to the parser, it will consider that:
- name is blank (so it's owned by the last stated owner)
- TTL is 123

Where -based on RFC1035- it's expected to:
- see `123` as name
- use last stated or default TTL

### PR DESCRIPTION
**Pull request by a3dho3yn**
This PR will:
- prevent trimming whitespaces from the beginning of lines
- prevent considering first element of an entry as TTL
- consider both null and empty domain-name as not stated

Closes #72

### CODE REVIEW

**Comment by a3dho3yn** [comment]
The [`Parser::processLine`](https://github.com/Badcow/DNS/blob/1b54b9f7cc4f0e54194b3f97d901c8156c52c3e0/lib/Parser/Parser.php#L121) sets TTL for all records equal to the default value. Then the `null === $this->currentResourceRecord->getTtl()` criteria on [`Parser::populateWithLastStated`](https://github.com/Badcow/DNS/blob/1b54b9f7cc4f0e54194b3f97d901c8156c52c3e0/lib/Parser/Parser.php#L196) will be always false and the parser will never uses the last stated TTL (which is the desired behavior based on RFC1053).
> Omitted class and TTL values are default to the last explicitly stated values.

This is why `ReverseRecordTest::testParseReverseRecordFile` fails.

**Comment by a3dho3yn** [comment]
@samuelwilliams any comments?

**Comment by fshafiee** [comment]
That'd be nice if could see this merged to the main repo.

**Comment by a3dho3yn** [comment]
@samuelwilliams @srsbiz @skirmis is there any problem with this PR?

**Pull request merged**
